# Standards: 0.1
---
- name: Fact google-chrome user
  set_fact:
    google_chrome_user: "{{ google_chrome_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - google-chrome

- become: "{{ (google_chrome_user != ansible_user_id) | bool }}"
  become_user: "{{ google_chrome_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: google-chrome
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - google-chrome

    - name: Remove quarantine flag
      register: google_chrome_quarantine
      failed_when: google_chrome_quarantine.rc != 0 and "No such xattr" not in google_chrome_quarantine.stderr
      changed_when: google_chrome_quarantine.rc == 0
      command: xattr -d com.apple.quarantine /Applications/Google\ Chrome.app
      tags:
        - google-chrome

    - name: Install pidof package
      homebrew:
        name: pidof
      tags:
        - google-chrome

    - name: Check program running
      register: google_chrome_running
      check_mode: False
      failed_when: False
      changed_when: google_chrome_running.stdout | length > 0 | bool
      command: pidof Google\ Chrome
      tags:
        - google-chrome

    - name: Fact program running
      set_fact:
        google_chrome_started: "{{ google_chrome_running.stdout_lines | length > 0 | bool }}"
      tags:
        - google-chrome

...
